{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name, $app := .Values.applications }}
{{- if $app.enabled }}
---
# Pod disruption budgets protect availability during voluntary node maintenance.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
